FROM python:3.12-slim

WORKDIR /app

COPY requirements.frontend.txt .

RUN pip install --no-cache-dir -r requirements.frontend.txt

COPY . .

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
